config/routes.rb
Rails.application.routes.draw do

  resources :sits do
    member do
      get :sitter_response
      put :sitter_update
    end
  end

  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"
  get "signup_family" => "users#signup_family"
  get "signup_sitter" => "users#signup_sitter"

  root 'welcome#index'

  resources :kids

  resources :sitters do
    collection do
      get :search
    end
  end

  resources :families
  resources :users do
    collection do
      get :route_me
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  

end

app/models/kid.rb
class Kid < ActiveRecord::Base
	belongs_to :family
	has_many :sits, through: :families
	# validates :age, numericality: true
	# validates :gender, :family_id, presence: true
end

app/controllers/kids_controller.rb
class KidsController < ApplicationController
  skip_filter :ensure_current_sitter

  #GET '/kids'
  def index
    @kids = Kid.all
  end

  #GET '/kids/new'
  def new
    @kid = Kid.new
  end

  #GET '/kids/:id/edit'
  def edit
    @kid = Kid.find(params[:id])
  end

  def create
    @new_kid = Kid.new(kid_params)
    if @new_kid.save
      redirect_to kids_path
    else
      redirect_to new_kid_path
    end
  end

  def show
    @kid = Kid.find(params[:id])
  end

  def update
    @kid = Kid.find(params[:id])
    if @kid.update_attributes(kid_params)
      redirect_to :action => 'show', :id => @kid
    else
      @kids = Kid.find(:all)
      render :action => 'edit'
    end
  end

  def destroy
    Kid.find(params[:id]).destroy
    redirect_to kids_path
  end



  # PATCH "/kids/:id/change_kid"
  def change_kid
    @kid = Kid.find(params[:id])
    @kid.update_attributes
    redirect_to kids_path
  end

  private

  def kid_params
    params.require(:kid).permit!
  end
end

app/helpers/kids_helper.rb
module KidsHelper
end

app/views/kids/_form.html.haml
= form_for(@kid) do |n|
  .col-lg-8.col-md-8.col-sm-8.col-sm-offset-2.col-md-offset-2.col-lg-offset-2
    .panel.form_group
      = n.label "What's the Little Angel's name?"
      = n.text_field :name, class: "form-control"

      = n.label "How old is little tyke?"
      = n.text_field :age, class: "form-control"

      = n.label "And it's gender?"
      = n.text_field :gender, class: "form-control"

      = n.label "What would a sitter need to know about your child?"
      = n.text_area :comments, class: "form-control"

      = n.label "Family Name"
      = n.select :family_id, Family.all.collect { |f| [f.name, f.id] } 
    
    %br
    .col-lg-4.col-md-4.col-sm-4.col-sm-offset-4.col-md-offset-4.col-lg-offset-4
      = n.submit 'Save', class: "btn bt-default"
    %br
    %br

app/views/kids/edit.html.haml
%div(class="container-fluid form-new")
	%h2 Edit a Kid
	= simple_form_for(@kid, html: {class: 'form-vertical'}, method: :post) do |n|
		= render "form", n: n

	%br

app/views/kids/index.html.haml
%h2 Kids List
.col-lg4.col-md-4.col-sm-4.col-sm-offset-4.col-md-offset-4.col-lg-offset-4
  = link_to 'Add New Kid', new_kid_path, class: "btn btn-default green"
  %br
  %br


  - @kids.each do |kid|
    = link_to kid.name, kid_path(kid), class: "btn btn-default"
    %br
    %br

app/views/kids/new.html.haml
%div(class="container-fluid form-new")
	%h2 kids new page
	= simple_form_for(@kid, html: {class: 'form-vertical'}, url: "/kids", method: :post) do |n|
		= render "form", n: n

	%br

app/views/kids/show.html.haml
%h2 Kid Details
.col-lg8.col-md-8.col-sm-8.col-sm-offset-2.col-md-offset-2.col-lg-offset-2
  %table
    %tbody
      %tr
        %th Name:
        %th Age:
        %th Gender:
        %th Comments:
        %th Family:
      %tr
        %td{:width=>"20%"} 
          = @kid.name 
        %td{:width=>"20%"}
          = @kid.age
        %td{:width=>"20%"}
          = @kid.gender
        %td{:width=>"20%"}
          = @kid.comments
        %td{:width=>"20%"}
          = @kid.family.name
  %br
  %br
  .col-lg6.col-md-6.col-sm-6.col-sm-offset-3.col-md-offset-3.col-lg-offset-3
    = link_to 'Edit Kid', edit_kid_path(@kid), class: "btn btn-default green", method: :get
    %br
    %br
    = link_to 'Delete Kid', kid_path(@kid), class: "btn btn-default green", method: :delete