config/routes.rb
Rails.application.routes.draw do

  resources :sits do
    member do
      get :sitter_response
      put :sitter_update
    end
  end

  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"
  get "signup_family" => "users#signup_family"
  get "signup_sitter" => "users#signup_sitter"

  root 'welcome#index'

  resources :kids

  resources :sitters do
    collection do
      get :search
    end
  end

  resources :families
  resources :users do
    collection do
      get :route_me
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  

end

app/models/sit.rb
class Sit < ActiveRecord::Base
	has_many :families
	has_many :sitters
end

app/controllers/sits_controller.rb
class SitsController < ApplicationController
	skip_filter :ensure_current_sitter
	
	def index
		@sits = Sit.all
	end

	def create
		@new_sit = Sit.new(sit_params)
		if @new_sit.save
			redirect_to sits_path
		else
			render new_sit_path
		end
	end

	def new
		@new_sit = Sit.new
	end

	def edit
		@sit = Sit.find(params[:id])
	end

	def update
		@sit = Sit.find(params[:id])
		if @sit.update_attributes(sit_params)
			redirect_to sits_path
		end
	end

	def show

	end

	def destroy
		@sit = Sit.find(params[:id])
		@sit.destroy
		redirect_to sits_path
	end

	#sitter edits sit request to accept
	def sitter_response
		@sit = Sit.find(params[:id])
	end

	#put / patch request to update table with sitter response
	def sitter_update
		@sit = Sit.find(params[:id])
		if @sit.update_attributes(sit_params)
			redirect_to sits_path
		end
	end

	private

	def sit_params
		params.require(:sit).permit!
	end

end

app/helpers/sits_helper.rb
module SitsHelper
end

app/views/sits/_form.html.haml
_form.html.haml

app/views/sits/_nav_bar.html.haml
!!!
%html
  %head
    %title LocalSitterApp
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body

  .navbar.navbar-default
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", type: "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: "#"} SplashPage
    .navbar-collapse.collapse.navbar-responsive-collapse
      %ul.nav.navbar-nav
        %li.active
          %a{href: sits_path} SitsList
        %li
          %a{href: sitters_path} Sitters
        %li
          %a{href: families_path} Families
        %li
          %a{href: kids_path} Kids
        / %li.dropdown
        /   %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
        /     Dropdown
        /     %b.caret
        /   %ul.dropdown-menu
        /     %li
        /       %a{href: "#"} Action
        /     %li
        /       %a{href: "#"} Another action
        /     %li
        /       %a{href: "#"} Something else here
        /     %li.divider
        /     %li.dropdown-header Dropdown header
        /     %li
        /       %a{href: "#"} Separated link
        /     %li
        /       %a{href: "#"} One more separated link
      %form.navbar-form.navbar-left
        %input.form-control.col-lg-8{placeholder: "Search", type: "text"}/
      %ul.nav.navbar-nav.navbar-right
        %li
          %a{href: new_sit_path} Request a New Sit
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
            Dropdown
            %b.caret
          %ul.dropdown-menu
            %li
              %a{href: "#"} Action
            %li
              %a{href: "#"} Another action
            %li
              %a{href: "#"} Something else here
            %li.divider
            %li
              %a{href: "#"} Separated link
%br
  = yield

app/views/sits/edit.html.haml
%h2 Edit a Sit
.col-lg12.col-md-12.col-sm12
  .col-lg6.col-md-6.col-sm-6.col-sm-offset-3.col-md-offset-3.col-lg-offset-3
    = form_for @sit, url: "/sits/#{@sit.id}", method: :put do |f|
      = f.label "Date of sit"
      = f.date_field :date, class: "form-control"
      %br
      = f.label "Start Time"
      = f.time_field :start_time, class: "form-control"
      %br
      = f.label "End Time"
      = f.time_field :end_time, class: "form-control"
      %br
      = f.label "Status"
      = f.select :status, options_for_select(['SENT', 'WITHDRAWN']), class: "form-control"
      %br
      = f.submit "EDIT", class: "form-control"

app/views/sits/index.html.haml
%h2 Sits List
.col-lg6.col-md-6.col-sm-6.col-sm-offset-3.col-md-offset-3.col-lg-offset-3
  = link_to 'Add New Sit', new_sit_path, class: "btn btn-default"
  %br
  %br

  - @sits.each do |s|
    .green-border
      %br
      - fam = Family.find(s.family_id)
      %b #{fam.name} Family
      %br
      %br
      Date of sit:
      = s.date
      %br
      Start time:
      = s.start_time.strftime("%I:%M %p")
      %br
      End time:
      = s.end_time.strftime("%I:%M %p")
      %br
      Status:
      = s.status
      %br

    = link_to 'Edit Sit', edit_sit_path(s.id), class: "btn btn-default", method: :get
    %br
    = link_to 'Delete Sit', sit_path(s), class: "btn btn-default green", method: :delete
    %br
    -if s.status == 'SENT'
      = link_to "Accept Sit", sitter_response_sit_path(s), class: "btn btn-default blue", method: :get
    %br
    %br
    %br

app/views/sits/new.html.haml
%h2 Add New Sit Request
.col-lg4.col-md-4.col-sm-4.col-sm-offset-4.col-md-offset-4.col-lg-offset-4
  .panel.form_group
    = form_for @new_sit, url: "/sits" do |s|
      = s.label "Family"
      = s.select :family_id, Family.all.collect { |f| [f.name, f.id] }
      %br
      = s.label "Date of sit"
      = s.date_field :date, class: "form-control"
      %br
      = s.label "Start Time"
      = s.time_field :start_time, class: "form-control"
      %br
      = s.label "End Time"
      = s.time_field :end_time, class: "form-control"
      %br
      = s.hidden_field :status, value: "SUBMITTED"

      .col-lg-4.col-md-4.col-sm-4.col-sm-offset-4.col-md-offset-4.col-lg-offset-4
      = s.submit "Add", class: "btn bt-default"

      %br
      %br

app/views/sits/show.html.haml
show.html.haml

app/views/sits/sitter_response.html.haml
= form_for @sit, url: sitter_update_sit_path, method: :put do |f|
	- fam = Family.find(@sit.family_id)
        
	= f.select :sitter_id, Sitter.all.collect { |s| [s.name, s.id] }
	%br
	%br
	= f.label fam.name
	%b Family
	%br
	= f.label "Date of Sit:"
	= f.label "#{@sit.date}"
	%br
	= f.label "Start Time:"
	= f.label "#{@sit.start_time.strftime("%I:%M %p")}"
	%br
	= f.label "End Time:"
	= f.label "#{@sit.end_time.strftime("%I:%M %p")}"
	%br
	= f.hidden_field :status, value: "ACCEPTED"
	= f.submit "Accept Sit"