config/routes.rb
Rails.application.routes.draw do

  resources :sits do
    member do
      get :sitter_response
      put :sitter_update
    end
  end

  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"
  get "signup_family" => "users#signup_family"
  get "signup_sitter" => "users#signup_sitter"

  root 'welcome#index'

  resources :kids

  resources :sitters do
    collection do
      get :search
    end
  end

  resources :families
  resources :users do
    collection do
      get :route_me
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Local Sitter App
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default
      %a.navbar-brand.custom_title{href: "/"} The Sitter-Connection
      %button.navbar-toggle{"data-target" => "#collapse_menu", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .navbar-collapse.collapse.navbar-responsive-collapse#collapse_menu
        .nav.navbar-nav.pad_me
          =link_to "Sitters", sitters_path, class: "make_green pad_me"
          =link_to "Families", families_path, class: "make_green pad_me"
          =link_to "Sits", sits_path, class: "make_green pad_me"
          =link_to "Kids", kids_path, class: "make_green pad_me"
          %span.btn.btn-primary.btn-md.search_button{"data-target" => "#myModal", "data-toggle" => "modal"}
            Search Sitters

          - if current_user
            = current_user.role
            = "Logged in as #{current_user.email}"
            = link_to "Log Out", logout_path
          - else
            = link_to "Log In", login_path
  



- flash.each do |key, msg|
  = content_tag :div, msg, :id => "flash_#{key}", :class => "#{flash_class(key)}"

#primary-content
  = yield

#myModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
        %h4#myModalLabel.modal-title Search Sitters!
      .modal-body
        = render "sitters/search_form"
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close